### ISSUE TITLE
MissingPluginException on Android

### ISSUE THREAD

**Issue by radivojeostojic** [roam-ai/roam-flutter#2]
I got this message when I tried to run the _initialize_ on Android:

`Caught unhandled_exception: MissingPluginException(No implementation found for method initialize on channel roam_flutter)`

I also got this message on the **example** app.

**Comment by jothipriyadharshanr** [comment]
> I got this message when I tried to run the _initialize_ on Android:
> 
> `Caught unhandled_exception: MissingPluginException(No implementation found for method initialize on channel roam_flutter)`
> 
> I also got this message on the **example** app.

Hey @radivojeostojic The plugin currently supports only iOS and we are releasing the Android support by this week or earliest next week which is in QA process.

Thanks.

**Comment by radivojeostojic** [comment]
@jothipriyadharshanr I am also receiving this error after `flutter drive` is executed:

```
Could not determine the dependencies of task ':roam_flutter:compileDebugAidl'.
 Failed to query the value of task ':roam_flutter:compileDebugAidl' property 'aidlFrameworkProvider'.
    Failed to install the following SDK components:
         platforms;android-30 Android SDK Platform 30
     The SDK directory is not writable (/opt/android-sdk)
```
    
 Is this something that will be resolved with the release for Android support?

**Comment by ManojAdithya** [comment]
Hi @radivojeostojic We released the Android Support today with our [0.0.5](https://github.com/roam-ai/roam-flutter/releases/tag/0.0.5) version.

**Comment by jothipriyadharshanr** [comment]
> @jothipriyadharshanr I am also receiving this error after `flutter drive` is executed:
> 
> 
> 
> ```
> 
> Could not determine the dependencies of task ':roam_flutter:compileDebugAidl'.
> 
>  Failed to query the value of task ':roam_flutter:compileDebugAidl' property 'aidlFrameworkProvider'.
> 
>     Failed to install the following SDK components:
> 
>          platforms;android-30 Android SDK Platform 30
> 
>      The SDK directory is not writable (/opt/android-sdk)
> 
> ```
> 
>     
> 
>  Is this something that will be resolved with the release for Android support? 

The plug-in currently not updated with unit tests. So you won't be able to run flutter drive. You can use the example application for both iOS and Android now.

**Comment by ManojAdithya** [comment]
@radivojeostojic I was hoping to schedule a call with you set some goals and expectation before you start the integration. So during the integration you have everything you need.
